---

group: stable
dist: trusty
branches:
  only:
    - develop
    - master

language: python
python: "2.7"

env:
  - ANSIBLE_INSTALL_VERSION=1.9.4
  - ANSIBLE_INSTALL_VERSION=2.0.0.2

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible==${ANSIBLE_INSTALL_VERSION}

script:
  # Install Role Dependencies
  - make test_deps
  # Check the role/playbook's syntax.
  - ansible-playbook --syntax-check --list-tasks -i tests/inventory tests/test.yml
  # First run
  - cd tests/
  # Test the "build" stage
  - ansible-playbook -i inventory test.yml --tags=build --connection=local
  - >
    ansible-playbook -i inventory test.yml --tags=build --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  # Test the "configure" stage
  - ansible-playbook -i inventory test.yml --tags=configure --connection=local
  - >
    ansible-playbook -i inventory test.yml --tags=configure --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
